### ISSUE TITLE
Data loading multiprocessor error

### ISSUE THREAD

**Issue by telukir** [KerstenDoering/PubMedPortable#12]
Tried to execute PubMedParser.py with multiprocessors. With this command

`python PubMedParser.py -d asthma_db -p 4 -i /home/kiran/Projects/PubMedPortable/asthma`

gives following error only for a large set of 3 GB, for a smaller one 55MB error did not came

`titute, ACECR, Tehran, Iran.', 'grant_list_complete_yn': 'Y', 'start_page': None, 'pmid': 29299026, 'citation_status': 'PubMed-not-MEDLINE', 'vernacular_title': None, 'end_page': None})]
  warnings.warn("\nIntegrityError: "+str(error), Warning)
`

```
Traceback (most recent call last):
  File "PubMedParser.py", line 652, in <module>
    run(options.medline_path, options.clean, int(options.start), options.end, int(options.PROCESSES))
  File "PubMedParser.py", line 615, in run
    res = result.get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
TypeError: object of type 'NoneType' has no len()
```

**Comment by KerstenDoering** [comment]
Hi Kiran,

thanks for using PubMedPortable.

I reproduced your error and also found a few others for the selected data set. The error message is not related to a multiprocessing problem, but a parser error for some text attribute which is null. 

I did the following:
- search for diabetes (https://www.ncbi.nlm.nih.gov/pubmed/?term=diabetes)
- generate XML files with generate_efetch.py and efetch.sh for the downloaded PMID list (https://github.com/KerstenDoering/PubMedPortable/wiki#download-a-data-set), such that each XML file contains 100 PubMed IDs
- run create_schema.sql, PubMedDB.py and PubMedParser.py
- repeat the whole procedure with the search term asthma

These two data sets can be fully processed with my latest commit "Added null, unique, and length checks" for PubMedParser.py.

Best,
Kersten
